import React from 'react';
import { Bounty } from './component/Bounty'
import './App.css';

const bounties = [
  {
    id: 1,
    title: 'Principles',
    life: 10,
    lifeMax: 10,
    money: 3,
    moneyMax: 3,
    users: 1,
    programmers: 1,
    servers: 1,
    sourceCode: 2,
    references: 1,
    tags: ['github', 'docker', 'dvc'],
    tagLinks: ['https://github.com/urgent/thisbounty.com', 'https://github.com/urgent/hasura/blob/master/docker-compose.yaml', 'https://github.com/urgent/kaiterra'],
    hurtLog: [],
  },
  {
    id: 2,
    title: 'Goals',
    life: 10,
    lifeMax: 10,
    money: 3,
    moneyMax: 3,
    users: 1,
    programmers: 1,
    servers: 1,
    sourceCode: 2,
    references: 1,
    tags: ['github'],
    tagLinks: ['https://github.com/urgent/thisbounty.com#goals'],
    hurtLog: [],
  },
  {
    id: 3,
    title: 'Rules',
    life: 10,
    lifeMax: 10,
    money: 3,
    moneyMax: 3,
    users: 1,
    programmers: 1,
    servers: 1,
    sourceCode: 2,
    references: 1,
    tags: ['github'],
    tagLinks: ['https://github.com/urgent/thisbounty.com#rules'],
    hurtLog: [],
  },
  {
    id: 4,
    title: 'Bounties',
    life: 10,
    lifeMax: 10,
    money: 3,
    moneyMax: 3,
    users: 1,
    programmers: 1,
    servers: 1,
    sourceCode: 2,
    references: 1,
    tags: [],
    tagLinks: [],
    hurtLog: [],
  },
  {
    id: 5,
    title: 'Wordpress',
    life: 4,
    lifeMax: 5,
    money: 5,
    moneyMax: 5,
    users: 50,
    programmers: 2,
    servers: 1,
    sourceCode: 1,
    references: 0,
    tags: [],
    tagLinks: [],
    hurtLog: [''],
  },
  {
    id: 6,
    title: 'AWS EC2',
    life: 3,
    lifeMax: 3,
    money: 5,
    moneyMax: 5,
    users: 50,
    programmers: 2,
    servers: 1,
    sourceCode: 1,
    references: 0,
    tags: [],
    tagLinks: [],
    hurtLog: ['Slow in Australia'],
  },
  {
    id: 7,
    title: 'Hasura, Traefik, Souin',
    life: 2,
    lifeMax: 3,
    money: 10,
    moneyMax: 10,
    users: 10,
    programmers: 1,
    servers: 1,
    sourceCode: 1,
    references: 1,
    tags: [],
    tagLinks: [],
    hurtLog: ['Needs Souin caching'],
  },
  {
    id: 8,
    title: 'DVC',
    life: 2,
    lifeMax: 4,
    money: 10,
    moneyMax: 10,
    users: 5,
    programmers: 1,
    servers: 1,
    sourceCode: 0,
    references: 0,
    tags: [],
    tagLinks: [],
    hurtLog: ['Interface for extract, dimensions', 'PyTorch'],
  },
  {
    id: 9,
    title: 'React',
    life: 3,
    lifeMax: 3,
    money: 10,
    moneyMax: 10,
    users: 0,
    programmers: 1,
    servers: 2,
    sourceCode: 0,
    references: 0,
    tags: [],
    tagLinks: [],
    hurtLog: [],
  },
  {
    id: 10,
    title: 'Relay',
    life: 3,
    lifeMax: 3,
    money: 10,
    moneyMax: 10,
    users: 0,
    programmers: 1,
    servers: 2,
    sourceCode: 0,
    references: 0,
    tags: [],
    tagLinks: [],
    hurtLog: [],
  },
  {
    id: 10,
    title: 'Google Cloud',
    life: 2,
    lifeMax: 3,
    money: 0,
    moneyMax: 10,
    users: 0,
    programmers: 1,
    servers: 1,
    sourceCode: 0,
    references: 0,
    tags: [],
    tagLinks: [],
    hurtLog: ['RAM'],
  },
]

function App() {
  return (
    <div className="App">
      <header className="App-header"><a href="/">thisbounty.com</a></header>
      <main>
        {bounties.map(bounty => <Bounty {...bounty} />)}
      </main>
      <footer>
        <ul>
          <li><a href="https://github.com/urgent/thisbounty.com" style={{ color: "#fff" }}>readme.md</a></li>
          <li><a href="https://docs.google.com/spreadsheets/d/1RSD6Kz04bKAGty_Z_gvSYc_Gu4QtAcTPTuvkK752mEw/edit?usp=sharing" style={{ color: "#fff" }}>Bounties</a></li>
        </ul>
      </footer>
    </div>
  );
}

export default App;
